services:
  backend:
    build: ./backend
    volumes:
      - ./backend:/app
      - /app/node_modules # Don't overwrite container modules with host ones
    environment:
      - NODE_ENV=development
    env_file:
      - /backend/.env

  frontend:
    build: ./frontend
    volumes:
      - ./frontend:/app
      - /app/node_modules

  proxy:
    image: nginx:alpine
    volumes:
      - ./proxy/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80" # This is your main entry point
    depends_on:
      - frontend
      - backend